name: Apprentice Wordsmith
baseurl: doublejay9.github.io/blog3/
description: A Writer's Blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

excerpt_separator: "<!--excerpt-->"
