name: Apprentice Wordsmith
baseurl: https://apprenticewordsmith.com
description: A Writer's Blog

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

excerpt_separator: "<!--excerpt-->"
